/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ASSETS_A_FILES           46
#define MMAP_ASSETS_A_CHECKSUM        0x788C

enum MMAP_ASSETS_A_LISTS {
    MMAP_ASSETS_A_ANGRY_AAF = 0,        /*!< angry.aaf */
    MMAP_ASSETS_A_ANOYING_AAF = 1,        /*!< anoying.aaf */
    MMAP_ASSETS_A_BINGO_AAF = 2,        /*!< bingo.aaf */
    MMAP_ASSETS_A_BLINK_AAF = 3,        /*!< blink.aaf */
    MMAP_ASSETS_A_BRAKING_AAF = 4,        /*!< braking.aaf */
    MMAP_ASSETS_A_CHARGING_AAF = 5,        /*!< charging.aaf */
    MMAP_ASSETS_A_COMFORT_AAF = 6,        /*!< comfort.aaf */
    MMAP_ASSETS_A_CONFIDENT_AAF = 7,        /*!< confident.aaf */
    MMAP_ASSETS_A_CONFUSED_AAF = 8,        /*!< confused.aaf */
    MMAP_ASSETS_A_CONNECTING_AAF = 9,        /*!< connecting.aaf */
    MMAP_ASSETS_A_CRYING_AAF = 10,        /*!< crying.aaf */
    MMAP_ASSETS_A_CURIOUS_AAF = 11,        /*!< curious.aaf */
    MMAP_ASSETS_A_CUTE_AAF = 12,        /*!< cute.aaf */
    MMAP_ASSETS_A_DEEPSLEEP_AAF = 13,        /*!< deepsleep.aaf */
    MMAP_ASSETS_A_DEFAULT_AAF = 14,        /*!< default.aaf */
    MMAP_ASSETS_A_DELICIOUS_AAF = 15,        /*!< delicious.aaf */
    MMAP_ASSETS_A_DIZZY_AAF = 16,        /*!< dizzy.aaf */
    MMAP_ASSETS_A_EMBARRASSED_AAF = 17,        /*!< embarrassed.aaf */
    MMAP_ASSETS_A_FLAG_AAF = 18,        /*!< flag.aaf */
    MMAP_ASSETS_A_FUNNY_AAF = 19,        /*!< funny.aaf */
    MMAP_ASSETS_A_GLASSES_AAF = 20,        /*!< glasses.aaf */
    MMAP_ASSETS_A_HAPPY_AAF = 21,        /*!< happy.aaf */
    MMAP_ASSETS_A_KNOCKING_AAF = 22,        /*!< knocking.aaf */
    MMAP_ASSETS_A_LAUGHING_AAF = 23,        /*!< laughing.aaf */
    MMAP_ASSETS_A_LISTENING_AAF = 24,        /*!< listening.aaf */
    MMAP_ASSETS_A_LOOKAROUND_AAF = 25,        /*!< lookaround.aaf */
    MMAP_ASSETS_A_LOVING_AAF = 26,        /*!< loving.aaf */
    MMAP_ASSETS_A_LOWPOWER_AAF = 27,        /*!< lowpower.aaf */
    MMAP_ASSETS_A_MUSIC_AAF = 28,        /*!< music.aaf */
    MMAP_ASSETS_A_NETERROR_AAF = 29,        /*!< neterror.aaf */
    MMAP_ASSETS_A_RELAXED_AAF = 30,        /*!< relaxed.aaf */
    MMAP_ASSETS_A_SAD_AAF = 31,        /*!< sad.aaf */
    MMAP_ASSETS_A_SAFEBELT_AAF = 32,        /*!< safebelt.aaf */
    MMAP_ASSETS_A_SAYHELLO_AAF = 33,        /*!< sayhello.aaf */
    MMAP_ASSETS_A_SCANINGWIFI_AAF = 34,        /*!< scaningwifi.aaf */
    MMAP_ASSETS_A_SHOCKED_AAF = 35,        /*!< shocked.aaf */
    MMAP_ASSETS_A_SILLY_AAF = 36,        /*!< silly.aaf */
    MMAP_ASSETS_A_SLEEPY_AAF = 37,        /*!< sleepy.aaf */
    MMAP_ASSETS_A_SPEEDING_AAF = 38,        /*!< speeding.aaf */
    MMAP_ASSETS_A_SURPRISE_AAF = 39,        /*!< surprise.aaf */
    MMAP_ASSETS_A_THINKING_AAF = 40,        /*!< thinking.aaf */
    MMAP_ASSETS_A_TURNLEFT_AAF = 41,        /*!< turnleft.aaf */
    MMAP_ASSETS_A_TURNRIGHT_AAF = 42,        /*!< turnright.aaf */
    MMAP_ASSETS_A_WAITINGCONF_AAF = 43,        /*!< waitingconf.aaf */
    MMAP_ASSETS_A_WINKING_AAF = 44,        /*!< winking.aaf */
    MMAP_ASSETS_A_YAWNING_AAF = 45,        /*!< yawning.aaf */
};
