/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_MOJI_EMOJI_FILES           45
#define MMAP_MOJI_EMOJI_CHECKSUM        0x5388

enum MMAP_MOJI_EMOJI_LISTS {
    MMAP_MOJI_EMOJI_ANGRY_AAF = 0,        /*!< angry.aaf */
    MMAP_MOJI_EMOJI_ANOYING_AAF = 1,        /*!< anoying.aaf */
    MMAP_MOJI_EMOJI_BINGO_AAF = 2,        /*!< bingo.aaf */
    MMAP_MOJI_EMOJI_BRAKING_AAF = 3,        /*!< braking.aaf */
    MMAP_MOJI_EMOJI_CHARGING_AAF = 4,        /*!< charging.aaf */
    MMAP_MOJI_EMOJI_COMFORT_AAF = 5,        /*!< comfort.aaf */
    MMAP_MOJI_EMOJI_CONFIDENT_AAF = 6,        /*!< confident.aaf */
    MMAP_MOJI_EMOJI_CONFUSED_AAF = 7,        /*!< confused.aaf */
    MMAP_MOJI_EMOJI_CONNECTING_AAF = 8,        /*!< connecting.aaf */
    MMAP_MOJI_EMOJI_CRYING_AAF = 9,        /*!< crying.aaf */
    MMAP_MOJI_EMOJI_CURIOUS_AAF = 10,        /*!< curious.aaf */
    MMAP_MOJI_EMOJI_CUTE_AAF = 11,        /*!< cute.aaf */
    MMAP_MOJI_EMOJI_DEEPSLEEP_AAF = 12,        /*!< deepsleep.aaf */
    MMAP_MOJI_EMOJI_DEFAULT_AAF = 13,        /*!< default.aaf */
    MMAP_MOJI_EMOJI_DELICIOUS_AAF = 14,        /*!< delicious.aaf */
    MMAP_MOJI_EMOJI_DIZZY_AAF = 15,        /*!< dizzy.aaf */
    MMAP_MOJI_EMOJI_EMBARRASSED_AAF = 16,        /*!< embarrassed.aaf */
    MMAP_MOJI_EMOJI_FLAG_AAF = 17,        /*!< flag.aaf */
    MMAP_MOJI_EMOJI_FUNNY_AAF = 18,        /*!< funny.aaf */
    MMAP_MOJI_EMOJI_GLASSES_AAF = 19,        /*!< glasses.aaf */
    MMAP_MOJI_EMOJI_HAPPY_AAF = 20,        /*!< happy.aaf */
    MMAP_MOJI_EMOJI_KNOCKING_AAF = 21,        /*!< knocking.aaf */
    MMAP_MOJI_EMOJI_LAUGHING_AAF = 22,        /*!< laughing.aaf */
    MMAP_MOJI_EMOJI_LISTENING_AAF = 23,        /*!< listening.aaf */
    MMAP_MOJI_EMOJI_LOOKAROUND_AAF = 24,        /*!< lookaround.aaf */
    MMAP_MOJI_EMOJI_LOVING_AAF = 25,        /*!< loving.aaf */
    MMAP_MOJI_EMOJI_LOWPOWER_AAF = 26,        /*!< lowpower.aaf */
    MMAP_MOJI_EMOJI_MUSIC_AAF = 27,        /*!< music.aaf */
    MMAP_MOJI_EMOJI_NETERROR_AAF = 28,        /*!< neterror.aaf */
    MMAP_MOJI_EMOJI_RELAXED_AAF = 29,        /*!< relaxed.aaf */
    MMAP_MOJI_EMOJI_SAD_AAF = 30,        /*!< sad.aaf */
    MMAP_MOJI_EMOJI_SAFEBELT_AAF = 31,        /*!< safebelt.aaf */
    MMAP_MOJI_EMOJI_SAYHELLO_AAF = 32,        /*!< sayhello.aaf */
    MMAP_MOJI_EMOJI_SCANINGWIFI_AAF = 33,        /*!< scaningwifi.aaf */
    MMAP_MOJI_EMOJI_SHOCKED_AAF = 34,        /*!< shocked.aaf */
    MMAP_MOJI_EMOJI_SILLY_AAF = 35,        /*!< silly.aaf */
    MMAP_MOJI_EMOJI_SLEEPY_AAF = 36,        /*!< sleepy.aaf */
    MMAP_MOJI_EMOJI_SPEEDING_AAF = 37,        /*!< speeding.aaf */
    MMAP_MOJI_EMOJI_SURPRISE_AAF = 38,        /*!< surprise.aaf */
    MMAP_MOJI_EMOJI_THINKING_AAF = 39,        /*!< thinking.aaf */
    MMAP_MOJI_EMOJI_TURNLEFT_AAF = 40,        /*!< turnleft.aaf */
    MMAP_MOJI_EMOJI_TURNRIGHT_AAF = 41,        /*!< turnright.aaf */
    MMAP_MOJI_EMOJI_WAITINGCONF_AAF = 42,        /*!< waitingconf.aaf */
    MMAP_MOJI_EMOJI_WINKING_AAF = 43,        /*!< winking.aaf */
    MMAP_MOJI_EMOJI_YAWNING_AAF = 44,        /*!< yawning.aaf */
};
